name: pro_location_tracker
description: "Professional-grade Flutter plugin for precise background location tracking."
version: 0.0.1
homepage: https://github.com/MrErkinjon/pro_location_tracker

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  plugin:
    platforms:
      android:
        package: uz.coder.pro_location_tracker
        pluginClass: ProLocationTrackerPlugin
      ios:
        pluginClass: ProLocationTrackerPlugin


